### ISSUE TITLE
add expansion for redirections

### ISSUE THREAD

**Issue by Cursedzyko** [pandaero/42_Core_minishell#26]
implement var_expansion and quote cleaning for redirection filenames

**Comment by pandaero** [comment]
added generic expansion fucntion [here](https://github.com/pandaero/42_Core_minishell/pull/42)

**Comment by Cursedzyko** [comment]
<img width="214" alt="Bildschirmfoto 2022-12-18 um 8 35 16 PM" src="https://user-images.githubusercontent.com/106797151/208316168-0d746eac-7e54-44ca-8b39-ab6b56da825b.png">

**Comment by Cursedzyko** [comment]
<img width="693" alt="Bildschirmfoto 2022-12-18 um 4 23 18 PM" src="https://user-images.githubusercontent.com/106797151/208316175-56eb737f-d9cf-4969-9dbc-5f68ce08601e.png">

**Comment by Cursedzyko** [comment]
<img width="1501" alt="Bildschirmfoto 2022-12-18 um 8 42 14 PM" src="https://user-images.githubusercontent.com/106797151/208316201-f79d70bf-5a0e-4f10-821b-f4b7acf16834.png">

**Comment by Cursedzyko** [comment]
Expansions not working correctly
