### ISSUE TITLE
echo is not working correctly and $

### ISSUE THREAD

**Issue by Cursedzyko** [pandaero/42_Core_minishell#41]
echo $'HO''ME' output should be HOME
$HOME should output /User/user
but it says that it is not command

**Comment by pandaero** [comment]
![image](https://user-images.githubusercontent.com/46035129/208292438-12369792-cf0a-4afa-bcab-294d2bb0f227.png)

I think it's okay if it isn't exactly the same, it is horrible to work out how to make it work

**Comment by Cursedzyko** [comment]
echo "            "'"    '            " "''"'" | cat -e

**Comment by Cursedzyko** [comment]
<img width="1880" alt="Bildschirmfoto 2022-12-18 um 8 25 14 PM" src="https://user-images.githubusercontent.com/106797151/208315519-ca03b381-0967-46c6-9f9d-95206afddf23.png">

**Comment by pandaero** [comment]
![image](https://user-images.githubusercontent.com/46035129/208703337-82a45663-766b-4652-b45c-18660a2d43df.png)
This one is solved. The quotes one..... is it worth it?
